#!/bin/sh
# Turn on dark mode universally.

# Usage in terminal (changes prompt's color as well):
# . enter_the_dark

# tell conforg to open new windows in dark mode
echo "dark" > $HOME/.config/conforg/colortheme

sed -i 's/^set\ background=light$/set\ background=dark/' $HOME/.config/nvim/init.vim
sed -i "s/^let\ g:airline_theme='sol'$/let\ g:airline_theme='solarized'/" $HOME/.config/nvim/init.vim

sed -i "s/^POWERLEVEL9K_COLOR_SCHEME='light'$/POWERLEVEL9K_COLOR_SCHEME='dark'/" $HOME/.zshrc

# TODO: xresources (mpd, ranger)

# switch running processes to dark mode
emacsclient --eval "(load-theme 'solarized-dark t)"
kitty @ set-colors -c --configured $HOME/.config/kitty/solarized-dark.conf

POWERLEVEL9K_COLOR_SCHEME='dark'
source  $CONFORG_DIR/contrib/powerlevel9k/powerlevel9k.zsh-theme
