#!/bin/sh
# Turn on light mode universally.

# tell conforg to open new windows in light mode
echo "light" > $HOME/.config/conforg/colorscheme
perl $HOME/cli-utils/reconfigure_kitty_colors.pl

sed -i 's/^set\ background=dark$/set\ background=light/' $HOME/.config/nvim/init.vim
sed -i "s/^let\ g:airline_theme='solarized'$/let\ g:airline_theme='sol'/" $HOME/.config/nvim/init.vim

sed -i "s/^POWERLEVEL9K_COLOR_SCHEME='dark'$/POWERLEVEL9K_COLOR_SCHEME='light'/" $HOME/.zshrc

# TODO: xresources (kitty, mpd, ranger)

emacsclient --eval "(load-theme 'solarized-light t)"

# if running interactively, switch running shell to light mode
if [[ $- == *i* ]]; then
  kitty @ set-colors -c --configured $HOME/.config/kitty/solarized-light.conf

  POWERLEVEL9K_COLOR_SCHEME='light'
  source  $CONFORG_DIR/contrib/powerlevel9k/powerlevel9k.zsh-theme
fi
