#!/bin/sh

# Kill proccesses via a fuzzy search

killarg=${1:-9}

pid=$(ps -ef | sed 1d | eval "fzf ${FZF_DEFAULT_OPTS} -m --header='[kill($killarg):process]'" | awk '{print $2}')

if [ "x$pid" != "x" ]
then
  echo $pid | xargs kill -${1:-9}
  fzkill
fi
