#!/bin/sh
SESSION=im

tmux -2 new-session -d -s $SESSION

tmux new-window -t $SESSION:1 -n 'Signal'
tmux select-window -t $SESSION:1
tmux send-keys "signal-desktop --start-in-tray" C-m

tmux new-window -t $SESSION:2 -n 'Riot'
tmux select-window -t $SESSION:2
tmux send-keys "riot-desktop --hidden" C-m
