#!/bin/sh

# Lock screen and turn off displays

case $1 in
  "lock")
    i3lock -c 000000;
    xset dpms force off ;;
  "cancel")
    exit 1 ;;
  *)
    i3lock -c 000000;
    xset dpms force off ;;
esac
