#!/usr/bin/bash

# Get fields from mpc, split by tabs.
IFS=$'\t' read album artist title \
  <<< "$(mpc --format="%album%\t%artist%\t%title%")"

notify-send --expire-time=5000 --app-name=mpd \
  --icon=audio-volume-high "Now playing" "$album ($artist) -- $title"
