#!/bin/sh

currenttime=$(date +%H:%M)
if [[ "$currenttime" > "18:00" ]] || [[ "$currenttime" < "06:00" ]]; then
  notify-send -a "Conforg" "It's night time" \
    "🌙🦇🦉🌃 Long and behold, let's enter the dark."
  source ~/cli-utils/enter_the_dark
else
  notify-send -a "Conforg" "It's day time" \
    "☀️🐿️🐶🏖️ Long and behold, let's enter the light."
  source ~/cli-utils/enter_the_light
fi
