#!/bin/sh

date '+%Y %b %d (%a) %I:%M%p'

case $BLOCK_BUTTON in
  1) emacsclient -n -c --eval "(org-agenda-list)" >/dev/null;;
	2) pgrep -x dunst >/dev/null && $HOME/.conforg/contrib/i3blocks-commands/daily_agenda.el 2>&1 | grep "mylife" | awk -F ':' '{print $3}' | xargs -I {} notify-send -a 'Agenda' {} ;;
	3) pgrep -x dunst >/dev/null && notify-send -a "Time/Date" "Instructions" "📅 Left click to open org-agenda<br>❓ Right click shows help" ;;
esac
