#!/bin/sh

case $BLOCK_BUTTON in
  1) i3-msg "exec $HOME/cli-utils/dmenuumount" > /dev/null 2>&1 ;;
	3) pgrep -x dunst >/dev/null && notify-send -a "Eject Devices" "Instructions" "⏏️ Left click to run dmenuumount<br>❓ Right click shows help" ;;
esac

if ! grep simple-mtpfs /etc/mtab; then
  droid=''
  droid_tail=''
else
  droid='(🤖 + '
  droid_tail=')'
fi

nusb=$(lsblk -nrpo "name,type,size,mountpoint" | awk '($2=="part"||$2=="crypt")&&$4!~/\/boot|\/home$|SWAP/&&length($4)>1{printf "%s (%s)\n",$4,$3}' | wc -l)

echo "${droid}${nusb}${droid_tail}"

