#!/bin/sh
[ "$(stat -c %y /tmp/weatherreport | awk '{print $1}')" != "$(date '+%Y-%m-%d')" ] && curl "wttr.in?m" | tee /tmp/weatherreport | perl -pe 's/\x1b\[[0-9;]*[a-zA-Z]//g' >> /tmp/weatherreport_plain


case $BLOCK_BUTTON in
    1) kitty -1 -e less -S /tmp/weatherreport_plain;;
    3) pgrep -x dunst >/dev/null && notify-send "<b>🌈 Weather module:</b>
- Click for wttr.in forecast.
☔: Chance of rain/snow
❄: Daily low
🌞: Daily high" ;;
esac

# Max probability of tomorrow
printf "%s" "$(sed '16q;d' /tmp/weatherreport | grep -wo "[0-9]*%" | sort -n | sed -e '$!d' | sed -e "s/^/☔ /g" | tr -d '\n')"

# Min/max temps of tomorrow
sed '13q;d' /tmp/weatherreport | grep -o "\\([^0-9]-\\)*[0-9]\\+" | sort -n -t 'm' -k 2n | sed -e 1b -e '$!d' | tr '\n|m' ' ' | awk '{print " ❄️",$1 "°C","🌞",$2 "°C"}'
